# Generated by Django 5.0.4 on 2024-04-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_films_actors_films_age_restrictions_films_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='tittle',
            new_name='title',
        ),
    ]
