# Generated by Django 5.0.4 on 2024-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_films_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RemoveField(
            model_name='films',
            name='age_restrictions',
        ),
        migrations.RemoveField(
            model_name='films',
            name='genre',
        ),
        migrations.AddField(
            model_name='films',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='actors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
